.travis.yml:
  # disable rubocop for now
  remove_includes:
    - env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
  includes:
    - rvm: 2.3.0
      env: PUPPET_GEM_VERSION="~> 4.10.4"
